name: ci-test
run-name: ci-test
on:
  push:
    branches:
      - main
jobs:
  build-container-image:
    runs-on: ubuntu-latest
    env:
      IMAGE: argoproj/rollouts-demo:blue
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run unit tests
        run: |
          echo "Running unit tests..."
      - name: Push prebuilt image
        run: |
          docker pull argoproj/rollouts-demo:blue
          docker tag argoproj/rollouts-demo:blue canary-deployment-test:${{ github.run_number }}
          docker push canary-deployment-test:${{ github.run_number }}
      - name: Modify image
        run: |
          yq --inplace \
              ".spec.template.spec.containers[0].image = \"${{ env.IMAGE }}\"" \
              canary-deployment-test/rollout.yaml
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Release ${{ env.IMAGE }} [skip ci]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
